/**
 * Baseball Savant pitch-by-pitch CSV columns, in Savant's order.
 *
 * Column names match the CSV header exactly, so Ryan Chasse's parser
 * (parseStatcastBulk in 8ctane-pitch-intelligence/athletes-v2.js) can run on
 * database rows unchanged. Source: https://baseballsavant.mlb.com/csv-docs,
 * corrected to the names the CSV actually uses (release_spin_rate,
 * hit_distance_sc) plus newer columns the docs page omits.
 *
 * This list and pitch_intel.savant_pitches in
 * uais/sql/create_pitch_intel_schema.sql must stay in sync. Columns Savant adds
 * later land in savant_pitches.raw_extra until they are added here and there.
 */

export type SavantColumnType = "text" | "float" | "int" | "bigint" | "date";

export const SAVANT_COLUMNS: ReadonlyArray<readonly [string, SavantColumnType]> = [
  ["pitch_type", "text"],
  ["game_date", "date"],
  ["release_speed", "float"],
  ["release_pos_x", "float"],
  ["release_pos_z", "float"],
  ["player_name", "text"],
  ["batter", "int"],
  ["pitcher", "int"],
  ["events", "text"],
  ["description", "text"],
  ["spin_dir", "float"],
  ["spin_rate_deprecated", "float"],
  ["break_angle_deprecated", "float"],
  ["break_length_deprecated", "float"],
  ["zone", "float"],
  ["des", "text"],
  ["game_type", "text"],
  ["stand", "text"],
  ["p_throws", "text"],
  ["home_team", "text"],
  ["away_team", "text"],
  ["type", "text"],
  ["hit_location", "float"],
  ["bb_type", "text"],
  ["balls", "float"],
  ["strikes", "float"],
  ["game_year", "float"],
  ["pfx_x", "float"],
  ["pfx_z", "float"],
  ["plate_x", "float"],
  ["plate_z", "float"],
  ["on_3b", "int"],
  ["on_2b", "int"],
  ["on_1b", "int"],
  ["outs_when_up", "float"],
  ["inning", "float"],
  ["inning_topbot", "text"],
  ["hc_x", "float"],
  ["hc_y", "float"],
  ["tfs_deprecated", "text"],
  ["tfs_zulu_deprecated", "text"],
  ["fielder_2", "int"],
  ["umpire", "text"],
  ["sv_id", "text"],
  ["vx0", "float"],
  ["vy0", "float"],
  ["vz0", "float"],
  ["ax", "float"],
  ["ay", "float"],
  ["az", "float"],
  ["sz_top", "float"],
  ["sz_bot", "float"],
  ["hit_distance_sc", "float"],
  ["launch_speed", "float"],
  ["launch_angle", "float"],
  ["effective_speed", "float"],
  ["release_spin_rate", "float"],
  ["release_extension", "float"],
  ["game_pk", "bigint"],
  ["fielder_3", "int"],
  ["fielder_4", "int"],
  ["fielder_5", "int"],
  ["fielder_6", "int"],
  ["fielder_7", "int"],
  ["fielder_8", "int"],
  ["fielder_9", "int"],
  ["release_pos_y", "float"],
  ["estimated_ba_using_speedangle", "float"],
  ["estimated_woba_using_speedangle", "float"],
  ["woba_value", "float"],
  ["woba_denom", "float"],
  ["babip_value", "float"],
  ["iso_value", "float"],
  ["launch_speed_angle", "float"],
  ["at_bat_number", "int"],
  ["pitch_number", "int"],
  ["pitch_name", "text"],
  ["home_score", "float"],
  ["away_score", "float"],
  ["bat_score", "float"],
  ["fld_score", "float"],
  ["post_away_score", "float"],
  ["post_home_score", "float"],
  ["post_bat_score", "float"],
  ["post_fld_score", "float"],
  ["if_fielding_alignment", "text"],
  ["of_fielding_alignment", "text"],
  ["spin_axis", "float"],
  ["delta_home_win_exp", "float"],
  ["delta_run_exp", "float"],
  ["bat_speed", "float"],
  ["swing_length", "float"],
  ["estimated_slg_using_speedangle", "float"],
  ["delta_pitcher_run_exp", "float"],
  ["hyper_speed", "float"],
  ["home_score_diff", "float"],
  ["bat_score_diff", "float"],
  ["home_win_exp", "float"],
  ["bat_win_exp", "float"],
  ["age_pit_legacy", "float"],
  ["age_bat_legacy", "float"],
  ["age_pit", "float"],
  ["age_bat", "float"],
  ["n_thruorder_pitcher", "float"],
  ["n_priorpa_thisgame_player_at_bat", "float"],
  ["pitcher_days_since_prev_game", "float"],
  ["batter_days_since_prev_game", "float"],
  ["pitcher_days_until_next_game", "float"],
  ["batter_days_until_next_game", "float"],
  ["api_break_z_with_gravity", "float"],
  ["api_break_x_arm", "float"],
  ["api_break_x_batter_in", "float"],
  ["arm_angle", "float"],
  ["attack_angle", "float"],
  ["attack_direction", "float"],
  ["swing_path_tilt", "float"],
  ["intercept_ball_minus_batter_pos_x_inches", "float"],
  ["intercept_ball_minus_batter_pos_y_inches", "float"],
] as const;

export const SAVANT_COLUMN_NAMES: ReadonlySet<string> = new Set(SAVANT_COLUMNS.map(([name]) => name));

/** Without these a pull is rejected: they identify the pitch or drive every core metric. */
export const REQUIRED_COLUMNS = [
  "game_pk",
  "game_date",
  "at_bat_number",
  "pitch_number",
  "pitcher",
  "pitch_type",
  "description",
  "balls",
  "strikes",
  "stand",
  "p_throws",
  "release_speed",
  "pfx_x",
  "pfx_z",
  "plate_x",
  "plate_z",
] as const;

/** Read by Ryan's parser; if missing, the matching feature shows "—" and the run is flagged. */
export const FEATURE_COLUMNS = [
  "player_name",
  "events",
  "zone",
  "bb_type",
  "home_team",
  "away_team",
  "inning_topbot",
  "release_spin_rate",
  "release_extension",
  "release_pos_x",
  "release_pos_z",
  "effective_speed",
  "vx0",
  "vy0",
  "vz0",
  "ax",
  "ay",
  "az",
  "launch_speed",
  "hc_x",
  "hc_y",
  "estimated_ba_using_speedangle",
  "estimated_woba_using_speedangle",
  "estimated_slg_using_speedangle",
  "delta_run_exp",
  "arm_angle",
] as const;
