/* AUTO-GENERATED by scripts/pitch-intel/sync-xarsenal.mjs. Do not edit by hand.
 * Source: Octane services/xArsenal/scoreArsenal.ts @ d2283d43
 *
 * SERVER-ONLY: contains the xArsenal benchmarks. Never import this from a
 * client component, and never copy it into a public repo.
 */
/* eslint-disable */
import {
  GradeLetter,
  type CompLevel,
  type DisplayType,
  type MetricStatus,
  type MetricThresholds,
  type PitchBenchmark,
  type PitchCategory,
  type PitchInput,
  type PitchResult,
  type PitchSubtype,
} from "./types";

const SUBTYPE_DISPLAY: Record<PitchSubtype, DisplayType> = {
  '4-Seam': '4-Seam',
  Sinker: 'Sinker',
  Cutter: 'Cutter',
  Slutter: 'Slider',
  Slider: 'Slider',
  'Gyro Slider': 'Slider',
  Sweeper: 'Sweeper',
  'Standard Curve': 'Curveball',
  '12-6 Curve': 'Curveball',
  'Gyro Curve': 'Curveball',
  'Change-Up': 'Changeup',
  Splitter: 'Splitter',
};

const VELOCITY_OFFSETS: Record<CompLevel, number> = {
  'Youth (14U)': 29,
  'High School': 17,
  College: 7,
  'Indy / Summer Ball': 4,
  MiLB: 2,
  MLB: 0,
};

const VELOCITY_WEIGHT_MULTIPLIERS: Record<CompLevel, number> = {
  'Youth (14U)': 2.1,
  'High School': 1.7,
  College: 1.15,
  'Indy / Summer Ball': 1.0,
  MiLB: 1.0,
  MLB: 1.0,
};

const NO_SPIN_EFF: MetricThresholds = {
  floor: 0,
  below: 0,
  avg: 0,
  good: 0,
  elite: 0,
  higherIsBetter: true,
  weight: 0,
};

const BENCHMARKS: Record<PitchSubtype, PitchBenchmark> = {
  '4-Seam': {
    subtype: '4-Seam',
    velocity: {
      floor: 78,
      below: 88,
      avg: 93,
      good: 96,
      elite: 100,
      higherIsBetter: true,
      weight: 0.3,
    },
    spinRate: {
      floor: 1700,
      below: 2050,
      avg: 2275,
      good: 2450,
      elite: 2650,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: 5,
      below: 10,
      avg: 16,
      good: 19,
      elite: 23,
      higherIsBetter: true,
      weight: 0.28,
    },
    hb: {
      floor: -2,
      below: 4,
      avg: 8,
      good: 11,
      elite: 14,
      higherIsBetter: true,
      weight: 0.08,
    },
    extension: {
      floor: 5.2,
      below: 5.9,
      avg: 6.6,
      good: 7.0,
      elite: 7.4,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -8.0,
      below: -6.5,
      avg: -5.0,
      good: -4.0,
      elite: -3.0,
      higherIsBetter: true,
      weight: 0.1,
    },
    spinEfficiency: {
      floor: 60,
      below: 75,
      avg: 87,
      good: 93,
      elite: 95,
      higherIsBetter: true,
      weight: 0.08,
    },
  },
  Sinker: {
    subtype: 'Sinker',
    velocity: {
      floor: 76,
      below: 86,
      avg: 92,
      good: 95,
      elite: 98,
      higherIsBetter: true,
      weight: 0.3,
    },
    spinRate: {
      floor: 1400,
      below: 1800,
      avg: 2100,
      good: 2300,
      elite: 2500,
      higherIsBetter: true,
      weight: 0.08,
    },
    ivb: {
      floor: 0,
      below: 3,
      avg: 7,
      good: 9,
      elite: 12,
      higherIsBetter: true,
      weight: 0.16,
    },
    hb: {
      floor: 6,
      below: 10,
      avg: 15,
      good: 17,
      elite: 20,
      higherIsBetter: true,
      weight: 0.34,
    },
    extension: {
      floor: 5.0,
      below: 5.7,
      avg: 6.4,
      good: 6.8,
      elite: 7.2,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -3.0,
      below: -5.0,
      avg: -6.5,
      good: -7.2,
      elite: -8.0,
      higherIsBetter: false,
      weight: 0.06,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  Cutter: {
    subtype: 'Cutter',
    velocity: {
      floor: 79,
      below: 84,
      avg: 89,
      good: 91,
      elite: 94,
      higherIsBetter: true,
      weight: 0.3,
    },
    spinRate: {
      floor: 1800,
      below: 2100,
      avg: 2400,
      good: 2600,
      elite: 2800,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: 2,
      below: 5,
      avg: 9,
      good: 12,
      elite: 15,
      higherIsBetter: true,
      weight: 0.16,
    },
    hb: {
      floor: 0,
      below: -2,
      avg: -4,
      good: -6,
      elite: -9,
      higherIsBetter: false,
      weight: 0.26,
    },
    extension: {
      floor: 5.0,
      below: 5.8,
      avg: 6.2,
      good: 6.6,
      elite: 7.0,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -4,
      avg: -5.2,
      good: -6.5,
      elite: -8.0,
      higherIsBetter: false,
      weight: 0.12,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  Slutter: {
    subtype: 'Slutter',
    velocity: {
      floor: 76,
      below: 81,
      avg: 86,
      good: 89,
      elite: 93,
      higherIsBetter: true,
      weight: 0.28,
    },
    spinRate: {
      floor: 1600,
      below: 2000,
      avg: 2300,
      good: 2500,
      elite: 2700,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: -4,
      below: 0,
      avg: 4,
      good: 7,
      elite: 10,
      higherIsBetter: true,
      weight: 0.14,
    },
    hb: {
      floor: 2,
      below: -1,
      avg: -6,
      good: -9,
      elite: -13,
      higherIsBetter: false,
      weight: 0.28,
    },
    extension: {
      floor: 4.8,
      below: 5.5,
      avg: 6.0,
      good: 6.4,
      elite: 6.8,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -4.5,
      avg: -6.0,
      good: -7.5,
      elite: -9.0,
      higherIsBetter: false,
      weight: 0.14,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  Slider: {
    subtype: 'Slider',
    velocity: {
      floor: 73,
      below: 79,
      avg: 84,
      good: 87,
      elite: 91,
      higherIsBetter: true,
      weight: 0.26,
    },
    spinRate: {
      floor: 1600,
      below: 1950,
      avg: 2250,
      good: 2450,
      elite: 2700,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: -8,
      below: -3,
      avg: 2,
      good: 5,
      elite: 8,
      higherIsBetter: true,
      weight: 0.14,
    },
    hb: {
      floor: 2,
      below: -2,
      avg: -8,
      good: -11,
      elite: -14,
      higherIsBetter: false,
      weight: 0.3,
    },
    extension: {
      floor: 4.5,
      below: 5.4,
      avg: 6.0,
      good: 6.4,
      elite: 6.8,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -5,
      avg: -7.0,
      good: -8.5,
      elite: -10,
      higherIsBetter: false,
      weight: 0.14,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  'Gyro Slider': {
    subtype: 'Gyro Slider',
    velocity: {
      floor: 74,
      below: 80,
      avg: 85,
      good: 88,
      elite: 91,
      higherIsBetter: true,
      weight: 0.26,
    },
    spinRate: {
      floor: 1800,
      below: 2100,
      avg: 2400,
      good: 2600,
      elite: 2800,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: -6,
      below: -2,
      avg: 1,
      good: 3,
      elite: 5,
      higherIsBetter: true,
      weight: 0.14,
    },
    hb: {
      floor: 2,
      below: -1,
      avg: -5,
      good: -8,
      elite: -11,
      higherIsBetter: false,
      weight: 0.26,
    },
    extension: {
      floor: 4.5,
      below: 5.4,
      avg: 6.0,
      good: 6.4,
      elite: 6.8,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -5,
      avg: -7.0,
      good: -8.0,
      elite: -9.5,
      higherIsBetter: false,
      weight: 0.1,
    },
    spinEfficiency: {
      floor: 60,
      below: 45,
      avg: 30,
      good: 22,
      elite: 15,
      higherIsBetter: false,
      weight: 0.08,
    },
  },
  Sweeper: {
    subtype: 'Sweeper',
    velocity: {
      floor: 70,
      below: 77,
      avg: 82,
      good: 86,
      elite: 90,
      higherIsBetter: true,
      weight: 0.2,
    },
    spinRate: {
      floor: 1600,
      below: 2000,
      avg: 2300,
      good: 2500,
      elite: 2750,
      higherIsBetter: true,
      weight: 0.08,
    },
    ivb: {
      floor: -5,
      below: -2,
      avg: 1,
      good: 4,
      elite: 7,
      higherIsBetter: true,
      weight: 0.08,
    },
    hb: {
      floor: -5,
      below: -10,
      avg: -17,
      good: -20,
      elite: -24,
      higherIsBetter: false,
      weight: 0.44,
    },
    extension: {
      floor: 4.5,
      below: 5.2,
      avg: 5.8,
      good: 6.2,
      elite: 6.6,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -4.5,
      avg: -6.5,
      good: -7.5,
      elite: -9.0,
      higherIsBetter: false,
      weight: 0.14,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  'Standard Curve': {
    subtype: 'Standard Curve',
    velocity: {
      floor: 65,
      below: 71,
      avg: 78,
      good: 82,
      elite: 86,
      higherIsBetter: true,
      weight: 0.2,
    },
    spinRate: {
      floor: 1600,
      below: 2000,
      avg: 2300,
      good: 2550,
      elite: 2800,
      higherIsBetter: true,
      weight: 0.12,
    },
    ivb: {
      floor: -3,
      below: -6,
      avg: -11,
      good: -14,
      elite: -18,
      higherIsBetter: false,
      weight: 0.24,
    },
    hb: {
      floor: 4,
      below: 0,
      avg: -5,
      good: -8,
      elite: -12,
      higherIsBetter: false,
      weight: 0.18,
    },
    extension: {
      floor: 4.5,
      below: 5.2,
      avg: 5.8,
      good: 6.2,
      elite: 6.6,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -3,
      below: -5.5,
      avg: -8.0,
      good: -9.5,
      elite: -11.5,
      higherIsBetter: false,
      weight: 0.12,
    },
    spinEfficiency: {
      floor: 45,
      below: 60,
      avg: 76,
      good: 86,
      elite: 94,
      higherIsBetter: true,
      weight: 0.08,
    },
  },
  '12-6 Curve': {
    subtype: '12-6 Curve',
    velocity: {
      floor: 65,
      below: 71,
      avg: 77,
      good: 81,
      elite: 85,
      higherIsBetter: true,
      weight: 0.18,
    },
    spinRate: {
      floor: 1600,
      below: 2050,
      avg: 2350,
      good: 2650,
      elite: 2900,
      higherIsBetter: true,
      weight: 0.12,
    },
    ivb: {
      floor: -3,
      below: -8,
      avg: -15,
      good: -17,
      elite: -21,
      higherIsBetter: false,
      weight: 0.28,
    },
    hb: {
      floor: 10,
      below: 6,
      avg: 2,
      good: 1,
      elite: 0,
      higherIsBetter: false,
      weight: 0.12,
    },
    extension: {
      floor: 4.5,
      below: 5.2,
      avg: 5.8,
      good: 6.2,
      elite: 6.6,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -3,
      below: -6,
      avg: -9.0,
      good: -10,
      elite: -12,
      higherIsBetter: false,
      weight: 0.14,
    },
    spinEfficiency: {
      floor: 45,
      below: 62,
      avg: 78,
      good: 88,
      elite: 96,
      higherIsBetter: true,
      weight: 0.1,
    },
  },
  'Gyro Curve': {
    subtype: 'Gyro Curve',
    velocity: {
      floor: 67,
      below: 72,
      avg: 79,
      good: 82,
      elite: 86,
      higherIsBetter: true,
      weight: 0.2,
    },
    spinRate: {
      floor: 1400,
      below: 1800,
      avg: 2150,
      good: 2400,
      elite: 2650,
      higherIsBetter: true,
      weight: 0.1,
    },
    ivb: {
      floor: -1,
      below: -4,
      avg: -7,
      good: -10,
      elite: -14,
      higherIsBetter: false,
      weight: 0.22,
    },
    hb: {
      floor: 6,
      below: 2,
      avg: -2,
      good: -5,
      elite: -9,
      higherIsBetter: false,
      weight: 0.14,
    },
    extension: {
      floor: 4.5,
      below: 5.2,
      avg: 5.8,
      good: 6.2,
      elite: 6.6,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -3,
      below: -5.5,
      avg: -8.0,
      good: -9.5,
      elite: -11.0,
      higherIsBetter: false,
      weight: 0.14,
    },
    spinEfficiency: {
      floor: 60,
      below: 48,
      avg: 36,
      good: 27,
      elite: 18,
      higherIsBetter: false,
      weight: 0.14,
    },
  },
  'Change-Up': {
    subtype: 'Change-Up',
    velocity: {
      floor: 73,
      below: 79,
      avg: 85,
      good: 87,
      elite: 90,
      higherIsBetter: true,
      weight: 0.24,
    },
    spinRate: {
      floor: 1000,
      below: 1400,
      avg: 1800,
      good: 2050,
      elite: 2250,
      higherIsBetter: true,
      weight: 0.08,
    },
    ivb: {
      floor: 13,
      below: 10,
      avg: 7,
      good: 5,
      elite: 3,
      higherIsBetter: false,
      weight: 0.18,
    },
    hb: {
      floor: 5,
      below: 9,
      avg: 15,
      good: 17,
      elite: 21,
      higherIsBetter: true,
      weight: 0.26,
    },
    extension: {
      floor: 5.0,
      below: 5.8,
      avg: 6.3,
      good: 6.7,
      elite: 7.0,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -4.5,
      avg: -6.5,
      good: -7.5,
      elite: -9.0,
      higherIsBetter: false,
      weight: 0.1,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
  Splitter: {
    subtype: 'Splitter',
    velocity: {
      floor: 74,
      below: 80,
      avg: 86,
      good: 88,
      elite: 91,
      higherIsBetter: true,
      weight: 0.3,
    },
    spinRate: {
      floor: 1800,
      below: 1300,
      avg: 900,
      good: 600,
      elite: 350,
      higherIsBetter: false,
      weight: 0.08,
    },
    ivb: {
      floor: 8,
      below: 4,
      avg: 1,
      good: -1,
      elite: -4,
      higherIsBetter: false,
      weight: 0.22,
    },
    hb: {
      floor: 10,
      below: 6,
      avg: 3,
      good: 1,
      elite: 0,
      higherIsBetter: false,
      weight: 0.24,
    },
    extension: {
      floor: 5.0,
      below: 5.8,
      avg: 6.2,
      good: 6.6,
      elite: 7.0,
      higherIsBetter: true,
      weight: 0.06,
    },
    vaa: {
      floor: -2,
      below: -5,
      avg: -7.5,
      good: -9.0,
      elite: -11.0,
      higherIsBetter: false,
      weight: 0.1,
    },
    spinEfficiency: NO_SPIN_EFF,
  },
};

const CLAMP_RANGES: Record<
  keyof Omit<PitchInput, 'category'>,
  [number, number]
> = {
  velocity: [0, 115],
  spinRate: [0, 5000],
  ivb: [-40, 40],
  hb: [-40, 40],
  extension: [0, 15],
  vaa: [-15, 5],
  spinEfficiency: [0, 100],
};

function clamp(val: number, min: number, max: number): number {
  return Math.min(Math.max(val, min), max);
}

function monotoneCubicInterpolant(
  xs: readonly number[],
  ys: readonly number[],
): (x: number) => number {
  const n = xs.length;

  // Per-interval secant slopes
  const delta: number[] = [];
  for (let k = 0; k < n - 1; k++) {
    delta.push((ys[k + 1] - ys[k]) / (xs[k + 1] - xs[k]));
  }

  // Initial tangent estimates
  const tang: number[] = new Array(n);
  tang[0] = delta[0];
  tang[n - 1] = delta[n - 2];
  for (let k = 1; k < n - 1; k++) {
    tang[k] =
      Math.sign(delta[k - 1]) !== Math.sign(delta[k])
        ? 0
        : (delta[k - 1] + delta[k]) / 2;
  }

  // Fritsch-Carlson monotonicity step
  for (let k = 0; k < n - 1; k++) {
    if (delta[k] === 0) {
      tang[k] = 0;
      tang[k + 1] = 0;
    } else {
      const a = tang[k] / delta[k];
      const b = tang[k + 1] / delta[k];
      const h = Math.hypot(a, b);
      if (h > 3) {
        const tau = 3 / h;
        tang[k] = tau * a * delta[k];
        tang[k + 1] = tau * b * delta[k];
      }
    }
  }

  return (x: number): number => {
    // Linear extrapolation outside the domain using boundary tangents
    if (x <= xs[0]) return ys[0] + tang[0] * (x - xs[0]);
    if (x >= xs[n - 1]) return ys[n - 1] + tang[n - 1] * (x - xs[n - 1]);

    // Binary search for the containing interval
    let lo = 0;
    let hi = n - 2;
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1;
      if (xs[mid] <= x) lo = mid;
      else hi = mid - 1;
    }

    const h = xs[lo + 1] - xs[lo];
    const u = (x - xs[lo]) / h;
    const u2 = u * u;
    const u3 = u2 * u;

    // Cubic Hermite basis evaluation
    return (
      (2 * u3 - 3 * u2 + 1) * ys[lo] +
      (u3 - 2 * u2 + u) * h * tang[lo] +
      (-2 * u3 + 3 * u2) * ys[lo + 1] +
      (u3 - u2) * h * tang[lo + 1]
    );
  };
}

function scoreMetric(value: number, t: MetricThresholds): number {
  if (t.weight === 0) return 0;

  const sign = t.higherIsBetter ? 1 : -1;
  const v = sign * value;
  const f = sign * t.floor;
  const b = sign * t.below;
  const a = sign * t.avg;
  const g = sign * t.good;
  const e = sign * t.elite;

  // Extend one band-width below the defined floor so sub-floor improvements
  // still register — approaches 0 at softZero rather than hard-cutting at floor.
  const softZero = f - Math.max(b - f, 1);

  const raw = monotoneCubicInterpolant(
    [softZero, f, b, a, g, e],
    [0, 12, 35, 60, 80, 100],
  )(v);

  return Math.min(Math.max(raw, 0), 107);
}

function metricStatus(score: number): MetricStatus {
  if (score >= 80) return 'elite';
  if (score >= 65) return 'above_avg';
  if (score >= 50) return 'avg';
  if (score >= 35) return 'below_avg';
  return 'poor';
}

function letterGrade(score: number): string {
  if (score >= 90) return `${GradeLetter.A}+`;
  if (score >= 85) return GradeLetter.A;
  if (score >= 80) return `${GradeLetter.A}-`;
  if (score >= 75) return `${GradeLetter.B}+`;
  if (score >= 70) return GradeLetter.B;
  if (score >= 65) return `${GradeLetter.B}-`;
  if (score >= 60) return `${GradeLetter.C}+`;
  if (score >= 55) return GradeLetter.C;
  if (score >= 50) return `${GradeLetter.C}-`;
  return GradeLetter.D;
}

function gradeLabel(score: number): string {
  if (score >= 90) return 'Elite';
  if (score >= 80) return 'Plus';
  if (score >= 70) return 'Above Average';
  if (score >= 55) return 'Average';
  if (score >= 40) return 'Below Average';
  return 'Well Below Average';
}

function arsenalDescription(
  pitches: PitchResult[],
  arsenalScore: number,
): string {
  if (pitches.length === 0) return '';

  const sorted = [...pitches].sort((a, b) => b.score - a.score);
  const best = sorted[0].displayType;
  const worst = sorted[sorted.length - 1].displayType;
  const bestLabel = gradeLabel(sorted[0].score);

  if (pitches.length === 1) {
    return `Your ${best} is scoring at a ${bestLabel} level. Add more pitches to get a full arsenal grade.`;
  }
  if (arsenalScore >= 80) {
    return `Your ${best} is an elite weapon. Your overall arsenal is plus-graded — you have the tools to miss bats at any level.`;
  }
  if (arsenalScore >= 65) {
    return `Your ${best} grades out as a plus pitch. Developing your ${worst} will round out your arsenal and limit predictability.`;
  }
  return `Your ${best} is your best weapon. Improving your ${worst} will give you a more complete arsenal and keep hitters off balance.`;
}

const SUBTYPES_BY_CATEGORY: Record<PitchCategory, PitchSubtype[]> = {
  Fastball: ['4-Seam', 'Sinker', 'Cutter'],
  'Breaking Ball': [
    'Slutter',
    'Slider',
    'Gyro Slider',
    'Sweeper',
    'Standard Curve',
    '12-6 Curve',
    'Gyro Curve',
  ],
  'Off-Speed': ['Change-Up', 'Splitter'],
};

interface InteractionBonus {
  metrics: [
    keyof Omit<PitchInput, 'category'>,
    keyof Omit<PitchInput, 'category'>,
  ];
  maxBonus: number;
}

const INTERACTION_BONUSES: Partial<Record<PitchSubtype, InteractionBonus>> = {
  'Change-Up': { metrics: ['ivb', 'hb'], maxBonus: 5 },
  Splitter: { metrics: ['ivb', 'hb'], maxBonus: 4 },
  '12-6 Curve': { metrics: ['ivb', 'hb'], maxBonus: 4 },
  'Gyro Slider': { metrics: ['ivb', 'spinEfficiency'], maxBonus: 4 },
};

export type { InteractionBonus };
export {
  SUBTYPE_DISPLAY,
  VELOCITY_OFFSETS,
  VELOCITY_WEIGHT_MULTIPLIERS,
  NO_SPIN_EFF,
  BENCHMARKS,
  CLAMP_RANGES,
  clamp,
  monotoneCubicInterpolant,
  scoreMetric,
  metricStatus,
  letterGrade,
  gradeLabel,
  arsenalDescription,
  SUBTYPES_BY_CATEGORY,
  INTERACTION_BONUSES,
};
